// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIMMvZ5EoWCu44Gb8uac17tnz9k8uRUmY',
    appId: '1:878893537555:web:40d81bb18d864cf88662e6',
    messagingSenderId: '878893537555',
    projectId: 'studenttasktracker-b28de',
    authDomain: 'studenttasktracker-b28de.firebaseapp.com',
    storageBucket: 'studenttasktracker-b28de.firebasestorage.app',
    measurementId: 'G-R0J407DGT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCCEM-nI0a2ArsJspruMS72VT35Qcr8pQ',
    appId: '1:878893537555:android:6d01f0833b2e2c5a8662e6',
    messagingSenderId: '878893537555',
    projectId: 'studenttasktracker-b28de',
    storageBucket: 'studenttasktracker-b28de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG0o1SPfMFZr_1CfRcFQjEmflX82bh3Hg',
    appId: '1:878893537555:ios:cbc2ae24749b6cd68662e6',
    messagingSenderId: '878893537555',
    projectId: 'studenttasktracker-b28de',
    storageBucket: 'studenttasktracker-b28de.firebasestorage.app',
    iosBundleId: 'com.example.taskappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG0o1SPfMFZr_1CfRcFQjEmflX82bh3Hg',
    appId: '1:878893537555:ios:cbc2ae24749b6cd68662e6',
    messagingSenderId: '878893537555',
    projectId: 'studenttasktracker-b28de',
    storageBucket: 'studenttasktracker-b28de.firebasestorage.app',
    iosBundleId: 'com.example.taskappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIMMvZ5EoWCu44Gb8uac17tnz9k8uRUmY',
    appId: '1:878893537555:web:ecb22de0afe8dba78662e6',
    messagingSenderId: '878893537555',
    projectId: 'studenttasktracker-b28de',
    authDomain: 'studenttasktracker-b28de.firebaseapp.com',
    storageBucket: 'studenttasktracker-b28de.firebasestorage.app',
    measurementId: 'G-1EW9E4RENS',
  );
}
